In [ ]:
!pip install flair==0.8

In [ ]:
from flair.data import Sentence
from flair.models import SequenceTagger
from flair.models import TextClassifier

In [ ]:
sentence = Sentence('Washington University, which is located in Missouri, is named after George Washington.', use_tokenizer=False)
tokenized_sentence = Sentence('Washington University, which is located in Missouri, is named after George Washington.', use_tokenizer=True)

In [ ]:
print(sentence)
print(tokenized_sentence)

Sentence: "Washington University, which is located in Missouri, is named after George Washington."   [− Tokens: 12]
Sentence: "Washington University , which is located in Missouri , is named after George Washington ."   [− Tokens: 15]


In [ ]:
print(sentence.get_token(3))

Token: 3 which


In [ ]:
print(sentence[2])

Token: 3 which


In [ ]:
for token in sentence:
  print(token)

Token: 1 Washington
Token: 2 University,
Token: 3 which
Token: 4 is
Token: 5 located
Token: 6 in
Token: 7 Missouri,
Token: 8 is
Token: 9 named
Token: 10 after
Token: 11 George
Token: 12 Washington.


In [ ]:
from flair.embeddings import WordEmbeddings

In [ ]:
en_embedding = WordEmbeddings('glove')

In [ ]:
en_embedding.embed(sentence)

[Sentence: "Washington University, which is located in Missouri, is named after George Washington."   [− Tokens: 12]]

In [ ]:
for token in sentence:
    print(token)
    print(token.embedding)

Token: 1 Washington
tensor([-2.2048e-01, -1.1316e-01,  9.4277e-01, -3.9024e-01,  2.5004e-01,
        -4.1651e-01, -1.4640e-01,  2.3628e-03, -1.2966e-01, -1.1173e-01,
        -2.1546e-01, -8.6271e-01,  1.3817e-01,  3.3118e-01, -6.6500e-01,
         3.7134e-01,  2.0050e-01, -3.4055e-01, -1.2422e+00, -7.6653e-01,
        -1.1253e-02,  3.8440e-01, -5.0105e-02, -1.8869e-01,  1.0785e-01,
         1.7502e-01, -1.0167e-01, -5.7925e-01,  2.3529e-01,  3.2626e-02,
         3.2353e-01,  9.7457e-01,  4.5231e-01,  4.9740e-01, -8.8874e-01,
         4.9170e-01,  1.1230e-01, -2.1484e-01,  9.3187e-02,  4.7039e-01,
        -7.8776e-01, -6.8219e-01, -2.3741e-01,  2.2351e-01,  2.0269e-01,
        -1.0166e+00,  1.3095e-01, -2.3654e-01,  3.1501e-01, -3.1880e-01,
         5.9744e-01, -2.8722e-01,  2.9970e-01,  3.4877e-01, -1.6597e-01,
        -2.8483e+00,  3.2219e-01, -7.8469e-01,  1.3754e+00,  1.5050e-01,
        -8.5193e-01,  2.5303e-01,  2.0142e-01, -5.9176e-01,  8.9212e-02,
        -3.5561e-01,  2.6522e-0

In [ ]:
sentence[0].get_embedding()

tensor([-2.2048e-01, -1.1316e-01,  9.4277e-01, -3.9024e-01,  2.5004e-01,
        -4.1651e-01, -1.4640e-01,  2.3628e-03, -1.2966e-01, -1.1173e-01,
        -2.1546e-01, -8.6271e-01,  1.3817e-01,  3.3118e-01, -6.6500e-01,
         3.7134e-01,  2.0050e-01, -3.4055e-01, -1.2422e+00, -7.6653e-01,
        -1.1253e-02,  3.8440e-01, -5.0105e-02, -1.8869e-01,  1.0785e-01,
         1.7502e-01, -1.0167e-01, -5.7925e-01,  2.3529e-01,  3.2626e-02,
         3.2353e-01,  9.7457e-01,  4.5231e-01,  4.9740e-01, -8.8874e-01,
         4.9170e-01,  1.1230e-01, -2.1484e-01,  9.3187e-02,  4.7039e-01,
        -7.8776e-01, -6.8219e-01, -2.3741e-01,  2.2351e-01,  2.0269e-01,
        -1.0166e+00,  1.3095e-01, -2.3654e-01,  3.1501e-01, -3.1880e-01,
         5.9744e-01, -2.8722e-01,  2.9970e-01,  3.4877e-01, -1.6597e-01,
        -2.8483e+00,  3.2219e-01, -7.8469e-01,  1.3754e+00,  1.5050e-01,
        -8.5193e-01,  2.5303e-01,  2.0142e-01, -5.9176e-01,  8.9212e-02,
        -3.5561e-01,  2.6522e-01,  1.1283e+00, -3.7

In [ ]:
sentence[11].get_embedding()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
x = sentence[0].get_embedding()
print(x)


tensor([-2.2048e-01, -1.1316e-01,  9.4277e-01, -3.9024e-01,  2.5004e-01,
        -4.1651e-01, -1.4640e-01,  2.3628e-03, -1.2966e-01, -1.1173e-01,
        -2.1546e-01, -8.6271e-01,  1.3817e-01,  3.3118e-01, -6.6500e-01,
         3.7134e-01,  2.0050e-01, -3.4055e-01, -1.2422e+00, -7.6653e-01,
        -1.1253e-02,  3.8440e-01, -5.0105e-02, -1.8869e-01,  1.0785e-01,
         1.7502e-01, -1.0167e-01, -5.7925e-01,  2.3529e-01,  3.2626e-02,
         3.2353e-01,  9.7457e-01,  4.5231e-01,  4.9740e-01, -8.8874e-01,
         4.9170e-01,  1.1230e-01, -2.1484e-01,  9.3187e-02,  4.7039e-01,
        -7.8776e-01, -6.8219e-01, -2.3741e-01,  2.2351e-01,  2.0269e-01,
        -1.0166e+00,  1.3095e-01, -2.3654e-01,  3.1501e-01, -3.1880e-01,
         5.9744e-01, -2.8722e-01,  2.9970e-01,  3.4877e-01, -1.6597e-01,
        -2.8483e+00,  3.2219e-01, -7.8469e-01,  1.3754e+00,  1.5050e-01,
        -8.5193e-01,  2.5303e-01,  2.0142e-01, -5.9176e-01,  8.9212e-02,
        -3.5561e-01,  2.6522e-01,  1.1283e+00, -3.7

In [ ]:
y = sentence[11].get_embedding()
print(y)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])


In [ ]:
import torch

# Assignment-1

In [ ]:
z = x==y
print(z)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False])


In [ ]:
en_embedding.embed(tokenized_sentence)

[Sentence: "Washington University , which is located in Missouri , is named after George Washington ."   [− Tokens: 15]]

In [ ]:
for token in sentence:
  print(token)

Token: 1 Washington
Token: 2 University,
Token: 3 which
Token: 4 is
Token: 5 located
Token: 6 in
Token: 7 Missouri,
Token: 8 is
Token: 9 named
Token: 10 after
Token: 11 George
Token: 12 Washington.


In [ ]:
for token in tokenized_sentence:
    print(token)

Token: 1 Washington
Token: 2 University
Token: 3 ,
Token: 4 which
Token: 5 is
Token: 6 located
Token: 7 in
Token: 8 Missouri
Token: 9 ,
Token: 10 is
Token: 11 named
Token: 12 after
Token: 13 George
Token: 14 Washington
Token: 15 .


In [ ]:
for token in tokenized_sentence:
    print(token)
    print(token.embedding)

a = tokenized_sentence [-2].get_embedding()
b = tokenized_sentence[0].get_embedding()
a==b


Token: 1 Washington
tensor([-2.2048e-01, -1.1316e-01,  9.4277e-01, -3.9024e-01,  2.5004e-01,
        -4.1651e-01, -1.4640e-01,  2.3628e-03, -1.2966e-01, -1.1173e-01,
        -2.1546e-01, -8.6271e-01,  1.3817e-01,  3.3118e-01, -6.6500e-01,
         3.7134e-01,  2.0050e-01, -3.4055e-01, -1.2422e+00, -7.6653e-01,
        -1.1253e-02,  3.8440e-01, -5.0105e-02, -1.8869e-01,  1.0785e-01,
         1.7502e-01, -1.0167e-01, -5.7925e-01,  2.3529e-01,  3.2626e-02,
         3.2353e-01,  9.7457e-01,  4.5231e-01,  4.9740e-01, -8.8874e-01,
         4.9170e-01,  1.1230e-01, -2.1484e-01,  9.3187e-02,  4.7039e-01,
        -7.8776e-01, -6.8219e-01, -2.3741e-01,  2.2351e-01,  2.0269e-01,
        -1.0166e+00,  1.3095e-01, -2.3654e-01,  3.1501e-01, -3.1880e-01,
         5.9744e-01, -2.8722e-01,  2.9970e-01,  3.4877e-01, -1.6597e-01,
        -2.8483e+00,  3.2219e-01, -7.8469e-01,  1.3754e+00,  1.5050e-01,
        -8.5193e-01,  2.5303e-01,  2.0142e-01, -5.9176e-01,  8.9212e-02,
        -3.5561e-01,  2.6522e-0

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])

In [ ]:
from flair.embeddings import FlairEmbeddings

# init Flair embedding
flair_embedding_forward = FlairEmbeddings('news-forward')
sentence = Sentence('Washington University, which is located in Missouri, is named after George Washington.', use_tokenizer=False)
tokenized_sentence = Sentence('Washington University, which is located in Missouri, is named after George Washington.', use_tokenizer=True)

In [ ]:
flair_embedding_forward.embed(tokenized_sentence )

[Sentence: "Washington University , which is located in Missouri , is named after George Washington ."   [− Tokens: 15]]

In [ ]:
flair_embedding_forward.embed(sentence )

[Sentence: "Washington University, which is located in Missouri, is named after George Washington."   [− Tokens: 12]]

In [ ]:
for token in sentence:
    print(token)
    print(token.embedding)

Token: 1 Washington
tensor([ 3.6137e-03, -3.7161e-06, -2.9144e-02,  ..., -2.2946e-03,
         1.4192e-03,  2.5718e-04])
Token: 2 University,
tensor([ 5.7817e-06, -7.4450e-05,  4.7114e-02,  ...,  1.8468e-04,
         3.0291e-02,  2.3024e-02])
Token: 3 which
tensor([-0.0003,  0.0005,  0.0148,  ..., -0.0089, -0.0048,  0.0054])
Token: 4 is
tensor([ 0.0049, -0.0028,  0.1546,  ..., -0.0027,  0.0913,  0.0074])
Token: 5 located
tensor([-0.0100, -0.0006,  0.0825,  ...,  0.0004, -0.0016, -0.0010])
Token: 6 in
tensor([-1.0987e-02,  1.8763e-05,  7.6530e-02,  ...,  5.2130e-05,
         7.9720e-03,  3.0658e-02])
Token: 7 Missouri,
tensor([-0.0007, -0.0002,  0.0149,  ..., -0.0006,  0.0282,  0.0026])
Token: 8 is
tensor([ 0.0004, -0.0014,  0.2109,  ..., -0.0007,  0.0107,  0.0082])
Token: 9 named
tensor([ 9.8073e-04, -6.7419e-05,  7.4864e-02,  ...,  4.2381e-04,
        -1.2899e-02,  8.7380e-03])
Token: 10 after
tensor([ 3.8829e-02,  4.9541e-05,  9.8218e-02,  ..., -1.8325e-03,
         1.5523e-03,  1.36

In [ ]:
sentence[11]

Token: 12 Washington.

In [ ]:
sentence[0]

Token: 1 Washington

In [ ]:
for token in tokenized_sentence:
    print(token)
    print(token.embedding)

Token: 1 Washington
tensor([ 3.6137e-03, -3.7161e-06, -2.9144e-02,  ..., -2.2946e-03,
         1.4192e-03,  2.5718e-04])
Token: 2 University
tensor([ 4.9652e-04, -6.9346e-04, -2.1376e-01,  ..., -7.0234e-05,
        -1.3960e-03,  7.4919e-04])
Token: 3 ,
tensor([-4.0296e-05,  2.9115e-05,  6.2106e-02,  ...,  2.0762e-05,
        -1.9901e-02,  1.0584e-02])
Token: 4 which
tensor([-0.0005,  0.0004,  0.0358,  ..., -0.0035, -0.0067,  0.0031])
Token: 5 is
tensor([ 0.0045, -0.0022,  0.1370,  ..., -0.0019,  0.1306,  0.0056])
Token: 6 located
tensor([-0.0110, -0.0005,  0.0741,  ...,  0.0003, -0.0013, -0.0013])
Token: 7 in
tensor([-1.7291e-02,  2.4153e-05,  7.0391e-02,  ...,  6.4110e-05,
         6.5429e-03,  2.6719e-02])
Token: 8 Missouri
tensor([ 4.3470e-07,  8.4391e-05,  1.8153e-02,  ..., -3.1905e-05,
         7.0416e-03,  7.9550e-03])
Token: 9 ,
tensor([-1.3976e-04,  2.2443e-03,  3.1918e-02,  ...,  5.4086e-05,
         3.7566e-03,  9.4838e-03])
Token: 10 is
tensor([ 0.0039, -0.0014,  0.1891,  ..

In [ ]:
tokenized_sentence[0]

Token: 1 Washington

In [ ]:
tokenized_sentence[-2]

Token: 14 Washington

# Assignment-2
compared the representations obtained for 'Washington' for both sentences, tokenized and raw.

In [ ]:
r = sentence[11].get_embedding()
t =sentence[0].get_embedding()

In [ ]:

r==t

tensor([False, False, False,  ..., False, False, False])

In [ ]:
u = tokenized_sentence[11].get_embedding()
p =  tokenized_sentence[-2].get_embedding()
u==p

tensor([False, False, False,  ..., False, False, False])

In [ ]:
pos_tagger = SequenceTagger.load('pos')

2022-02-27 15:09:10,244 --------------------------------------------------------------------------------
2022-02-27 15:09:10,247 The model key 'pos' now maps to 'https://huggingface.co/flair/pos-english' on the HuggingFace ModelHub
2022-02-27 15:09:10,248  - The most current version of the model is automatically downloaded from there.
2022-02-27 15:09:10,250  - (you can alternatively manually download the original model at https://nlp.informatik.hu-berlin.de/resources/models/pos/en-pos-ontonotes-v0.5.pt)
2022-02-27 15:09:10,251 --------------------------------------------------------------------------------


Downloading:   0%|          | 0.00/249M [00:00<?, ?B/s]

2022-02-27 15:09:17,566 loading file /root/.flair/models/pos-english/a9a73f6cd878edce8a0fa518db76f441f1cc49c2525b2b4557af278ec2f0659e.121306ea62993d04cd1978398b68396931a39eb47754c8a06a87f325ea70ac63


In [ ]:
pos_tagger.predict(sentence)

In [ ]:
for postag in sentence.get_spans('pos'):
  print(postag)

Span [1]: "Washington"   [− Labels: NNP (1.0)]
Span [2]: "University,"   [− Labels: NNP (1.0)]
Span [3]: "which"   [− Labels: WDT (1.0)]
Span [4]: "is"   [− Labels: VBZ (1.0)]
Span [5]: "located"   [− Labels: VBN (0.9999)]
Span [6]: "in"   [− Labels: IN (1.0)]
Span [7]: "Missouri,"   [− Labels: NNP (1.0)]
Span [8]: "is"   [− Labels: VBZ (1.0)]
Span [9]: "named"   [− Labels: VBN (1.0)]
Span [10]: "after"   [− Labels: IN (0.9994)]
Span [11]: "George"   [− Labels: NNP (1.0)]
Span [12]: "Washington."   [− Labels: NNP (1.0)]


In [ ]:
print(sentence.to_tagged_string())

Washington <NNP> University, <NNP> which <WDT> is <VBZ> located <VBN> in <IN> Missouri, <NNP> is <VBZ> named <VBN> after <IN> George <NNP> Washington. <NNP>


In [ ]:
chunker = SequenceTagger.load('chunk')

2022-02-27 15:11:50,130 --------------------------------------------------------------------------------
2022-02-27 15:11:50,133 The model key 'chunk' now maps to 'https://huggingface.co/flair/chunk-english' on the HuggingFace ModelHub
2022-02-27 15:11:50,135  - The most current version of the model is automatically downloaded from there.
2022-02-27 15:11:50,140  - (you can alternatively manually download the original model at https://nlp.informatik.hu-berlin.de/resources/models/chunk/en-chunk-conll2000-v0.4.pt)
2022-02-27 15:11:50,141 --------------------------------------------------------------------------------


Downloading:   0%|          | 0.00/249M [00:00<?, ?B/s]

2022-02-27 15:11:57,308 loading file /root/.flair/models/chunk-english/5b53097d6763734ee8ace8de92db67a1ee2528d5df9c6d20ec8e3e6f6470b423.d81b7fd7a38422f2dbf40f6449b1c63d5ae5b959863aa0c2c1ce9116902e8b22


In [ ]:
chunker.predict(sentence)

In [ ]:
for chunktag in sentence.get_spans('np'):
  print(chunktag)

Span [1,2]: "Washington University,"   [− Labels: NP (0.7408)]
Span [3]: "which"   [− Labels: NP (0.9995)]
Span [4,5]: "is located"   [− Labels: VP (0.8574)]
Span [6]: "in"   [− Labels: PP (1.0)]
Span [7]: "Missouri,"   [− Labels: NP (0.9999)]
Span [8,9]: "is named"   [− Labels: VP (0.9624)]
Span [10]: "after"   [− Labels: PP (0.9981)]
Span [11,12]: "George Washington."   [− Labels: NP (0.798)]


In [ ]:
print(sentence.to_tagged_string())

Washington <NNP/B-NP> University, <NNP/E-NP> which <WDT/S-NP> is <VBZ/B-VP> located <VBN/E-VP> in <IN/S-PP> Missouri, <NNP/S-NP> is <VBZ/B-VP> named <VBN/E-VP> after <IN/S-PP> George <NNP/B-NP> Washington. <NNP/E-NP>


In [ ]:
ner_tagger = SequenceTagger.load('ner')

2022-02-27 15:13:13,515 --------------------------------------------------------------------------------
2022-02-27 15:13:13,519 The model key 'ner' now maps to 'https://huggingface.co/flair/ner-english' on the HuggingFace ModelHub
2022-02-27 15:13:13,521  - The most current version of the model is automatically downloaded from there.
2022-02-27 15:13:13,522  - (you can alternatively manually download the original model at https://nlp.informatik.hu-berlin.de/resources/models/ner/en-ner-conll03-v0.4.pt)
2022-02-27 15:13:13,523 --------------------------------------------------------------------------------


Downloading:   0%|          | 0.00/432M [00:00<?, ?B/s]

2022-02-27 15:13:26,196 loading file /root/.flair/models/ner-english/4f4cdab26f24cb98b732b389e6cebc646c36f54cfd6e0b7d3b90b25656e4262f.8baa8ae8795f4df80b28e7f7b61d788ecbb057d1dc85aacb316f1bd02837a4a4


In [ ]:
ner_tagger.predict(sentence)

In [ ]:
for entity in sentence.get_spans('ner'):
    print(entity)

Span [1,2]: "Washington University,"   [− Labels: ORG (0.8766)]
Span [7]: "Missouri,"   [− Labels: LOC (0.9987)]
Span [11,12]: "George Washington."   [− Labels: PER (0.9916)]


In [ ]:
print(sentence.to_tagged_string())

Washington <NNP/B-NP/B-ORG> University, <NNP/E-NP/E-ORG> which <WDT/S-NP> is <VBZ/B-VP> located <VBN/E-VP> in <IN/S-PP> Missouri, <NNP/S-NP/S-LOC> is <VBZ/B-VP> named <VBN/E-VP> after <IN/S-PP> George <NNP/B-NP/B-PER> Washington. <NNP/E-NP/E-PER>


In [ ]:
sem_tagger = SequenceTagger.load('frame')

2022-02-27 15:17:05,798 --------------------------------------------------------------------------------
2022-02-27 15:17:05,801 The model key 'frame' now maps to 'https://huggingface.co/flair/frame-english' on the HuggingFace ModelHub
2022-02-27 15:17:05,803  - The most current version of the model is automatically downloaded from there.
2022-02-27 15:17:05,806  - (you can alternatively manually download the original model at https://nlp.informatik.hu-berlin.de/resources/models/frame/en-frame-ontonotes-v0.4.pt)
2022-02-27 15:17:05,808 --------------------------------------------------------------------------------


Downloading:   0%|          | 0.00/291M [00:00<?, ?B/s]

2022-02-27 15:17:14,212 loading file /root/.flair/models/frame-english/c397b8bbddf56e35a7d4b64295712a42a1a9b7ccf430dff76d03c8c7e26b9707.fd7786a36026b383ca73a1413c0a29aa1e67551621b805a0d28ca547636353b9


In [ ]:
sem_tagger.predict(sentence)

In [ ]:
for event in sentence.get_spans('frame'):
  print(event)
print(sentence.to_tagged_string())

Span [4]: "is"   [− Labels: be.03 (0.9955)]
Span [5]: "located"   [− Labels: locate.01 (0.9831)]
Span [8]: "is"   [− Labels: be.03 (0.9987)]
Span [9]: "named"   [− Labels: name.01 (0.7091)]
Washington <NNP/B-NP/B-ORG> University, <NNP/E-NP/E-ORG> which <WDT/S-NP> is <VBZ/B-VP/be.03> located <VBN/E-VP/locate.01> in <IN/S-PP> Missouri, <NNP/S-NP/S-LOC> is <VBZ/B-VP/be.03> named <VBN/E-VP/name.01> after <IN/S-PP> George <NNP/B-NP/B-PER> Washington. <NNP/E-NP/E-PER>


In [ ]:
print(sentence.to_dict(tag_type='pos'))

{'text': 'Washington University, which is located in Missouri, is named after George Washington.', 'labels': [], 'entities': [{'text': 'Washington', 'start_pos': 0, 'end_pos': 10, 'labels': [NNP (1.0)]}, {'text': 'University,', 'start_pos': 11, 'end_pos': 22, 'labels': [NNP (1.0)]}, {'text': 'which', 'start_pos': 23, 'end_pos': 28, 'labels': [WDT (1.0)]}, {'text': 'is', 'start_pos': 29, 'end_pos': 31, 'labels': [VBZ (1.0)]}, {'text': 'located', 'start_pos': 32, 'end_pos': 39, 'labels': [VBN (0.9999)]}, {'text': 'in', 'start_pos': 40, 'end_pos': 42, 'labels': [IN (1.0)]}, {'text': 'Missouri,', 'start_pos': 43, 'end_pos': 52, 'labels': [NNP (1.0)]}, {'text': 'is', 'start_pos': 53, 'end_pos': 55, 'labels': [VBZ (1.0)]}, {'text': 'named', 'start_pos': 56, 'end_pos': 61, 'labels': [VBN (1.0)]}, {'text': 'after', 'start_pos': 62, 'end_pos': 67, 'labels': [IN (0.9994)]}, {'text': 'George', 'start_pos': 68, 'end_pos': 74, 'labels': [NNP (1.0)]}, {'text': 'Washington.', 'start_pos': 75, 'end_po

In [ ]:
print(sentence.to_dict(tag_type='chunk'))

{'text': 'Washington University, which is located in Missouri, is named after George Washington.', 'labels': [], 'entities': []}


In [ ]:
print(sentence.to_dict(tag_type='ner'))

{'text': 'Washington University, which is located in Missouri, is named after George Washington.', 'labels': [], 'entities': [{'text': 'Washington University,', 'start_pos': 0, 'end_pos': 22, 'labels': [ORG (0.8766)]}, {'text': 'Missouri,', 'start_pos': 43, 'end_pos': 52, 'labels': [LOC (0.9987)]}, {'text': 'George Washington.', 'start_pos': 68, 'end_pos': 86, 'labels': [PER (0.9916)]}]}


In [ ]:
print(sentence.to_dict(tag_type='frame'))

{'text': 'Washington University, which is located in Missouri, is named after George Washington.', 'labels': [], 'entities': [{'text': 'is', 'start_pos': 29, 'end_pos': 31, 'labels': [be.03 (0.9955)]}, {'text': 'located', 'start_pos': 32, 'end_pos': 39, 'labels': [locate.01 (0.9831)]}, {'text': 'is', 'start_pos': 53, 'end_pos': 55, 'labels': [be.03 (0.9987)]}, {'text': 'named', 'start_pos': 56, 'end_pos': 61, 'labels': [name.01 (0.7091)]}]}


In [ ]:
polarity_classifier = TextClassifier.load('en-sentiment')

2022-02-27 15:25:40,051 https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt not found in cache, downloading to /tmp/tmp7kies8j1


100%|██████████| 265512723/265512723 [00:12<00:00, 21370357.73B/s]

2022-02-27 15:25:52,865 copying /tmp/tmp7kies8j1 to cache at /root/.flair/models/sentiment-en-mix-distillbert_4.pt


2022-02-27 15:25:53,408 removing temp file /tmp/tmp7kies8j1
2022-02-27 15:25:53,449 loading file /root/.flair/models/sentiment-en-mix-distillbert_4.pt


Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [ ]:
polarity_classifier.predict(sentence)

In [ ]:
print(sentence.to_tagged_string())
print(sentence.labels)

Washington <NNP/B-NP/B-ORG> University, <NNP/E-NP/E-ORG> which <WDT/S-NP> is <VBZ/B-VP/be.03> located <VBN/E-VP/locate.01> in <IN/S-PP> Missouri, <NNP/S-NP/S-LOC> is <VBZ/B-VP/be.03> named <VBN/E-VP/name.01> after <IN/S-PP> George <NNP/B-NP/B-PER> Washington. <NNP/E-NP/E-PER>
[POSITIVE (0.9722)]


# Assignment-3
Used the loop structure to annotate and display the annotations of every sentence in one step per task.

In [ ]:
def _ner(a):
  sentence = Sentence(a)
  ner_tagger.predict(sentence)
  return sentence

def pos_(a):
  sentence = Sentence(a)
  pos_tagger.predict(sentence)
  return sentence


def _frame_(b):
  sentence = Sentence(b)
  sem_tagger.predict(sentence)
  sentence.to_tagged_string()
  return sentence


def _chunk_(b):
  sentence = Sentence(b)
  chunker.predict(sentence)
  return sentence

def _sentiment(a):
  sentence = Sentence(a)
  polarity_classifier.predict(sentence)
  return sentence

In [ ]:
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
 x = '''Jackson is placed in Microsoft located in Redmond.
 Redmond is coming to New York city.
 Redmond is coming to New York City .
 Redmond is coming to New York City.'''

In [ ]:
y = '''Redmond returned to New York City to return his hat .
 He had a look at different hats.'''

In [ ]:
z = '''This film hurts.
It is so bad that I am confused.'''

In [ ]:
a = sent_tokenize(x)
b= sent_tokenize(y)
c = sent_tokenize(z)

In [ ]:
k= ''' a,b,c'''

In [ ]:
n = k.split()

In [ ]:
print(n)

['a,b,c']


In [ ]:
for elements in n:
  for sentence in a:
    f = pos_(sentence)
    print(f)

  for sentence in a:
    e = _ner(sentence)
    print(e)

  for sentence in b:
    g = _frame_(sentence)
    print(g)

  for sentence in b:
    h = _chunk_(sentence)
    print(h)

  for sentence in c:
    i = _sentiment(sentence)
    print(i)

Sentence: "Jackson is placed in Microsoft located in Redmond ."   [− Tokens: 9  − Token-Labels: "Jackson <NNP> is <VBZ> placed <VBN> in <IN> Microsoft <NNP> located <VBN> in <IN> Redmond <NNP> . <.>"]
Sentence: "Redmond is coming to New York city ."   [− Tokens: 8  − Token-Labels: "Redmond <NNP> is <VBZ> coming <VBG> to <IN> New <NNP> York <NNP> city <NN> . <.>"]
Sentence: "Redmond is coming to New York City ."   [− Tokens: 8  − Token-Labels: "Redmond <NNP> is <VBZ> coming <VBG> to <IN> New <NNP> York <NNP> City <NNP> . <.>"]
Sentence: "Redmond is coming to New York City ."   [− Tokens: 8  − Token-Labels: "Redmond <NNP> is <VBZ> coming <VBG> to <IN> New <NNP> York <NNP> City <NNP> . <.>"]
Sentence: "Jackson is placed in Microsoft located in Redmond ."   [− Tokens: 9  − Token-Labels: "Jackson <S-PER> is placed in Microsoft <S-ORG> located in Redmond <S-LOC> ."]
Sentence: "Redmond is coming to New York city ."   [− Tokens: 8  − Token-Labels: "Redmond <S-PER> is coming to New <B-LOC> York